Develop
VitaliyFrolov/Israel-project pull request #5
Opened 2023-07-18 20:44 UTC by VitaliyFrolov

added route to pages

2023-07-18 21:09 UTC, creator-woow approved these changes
fix that shish

2023-07-18 21:09 UTC, creator-woow commented on src/app/App.tsx
> +        path: '/stores/:store/products/:product',
storeId productId

2023-07-18 21:09 UTC, creator-woow commented on src/app/lib/routes.ts
> +  Product = '/stores/:store/products/:product',
same

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Home/ui/StoreCard.module.scss
> +    text-decoration: none;
to reset

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Home/ui/StoreCard.tsx
> +    const { discountsCount, name, imgUrl, link, className } = props
url or path or something like that

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Home/ui/StoreCard.tsx
> +        <Link to={`${link}`} className={styles.link}>
delete ``

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Home/ui/StoresList.tsx
> +            link={item.link}
up

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Product/ui/Page.tsx
> +    const { store, product } = useParams();
up

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Store/ui/Page.module.scss
> +.filterWrapper {
filter ubrat

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Store/ui/Page.module.scss
> +.searchForm {
search already exists check ui/shared

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Store/ui/Page.module.scss
> +
same

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Store/ui/Page.tsx
> +    useEffect(() => {
infinity scroll delete

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Store/ui/Page.tsx
> +                <div className={styles.filterWrapper}>
already create filter in features/stores

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Stores/lib/dataURL.ts
>  export enum dataURL {
rename

2023-07-18 21:09 UTC, creator-woow commented on src/pages/Stores/ui/Page.tsx
> -                    <Checkbox text="Товары только со скидкой"/>
rename to label or caption

2023-07-18 21:09 UTC, creator-woow commented on src/shared/ui/Title/ui/Title.tsx
> +    children: string | ReactElement;
string only

2023-07-18 21:13 UTC, creator-woow requested changes
fix that shish

2023-07-22 15:37 UTC, creator-woow requested changes

2023-07-22 15:37 UTC, creator-woow commented on src/app/App.tsx
> +        path: '/stores',
use enum with paths

2023-07-22 15:37 UTC, creator-woow commented on src/features/StoresList/ui/StoreCard.tsx
> +        <Link to={`${url}`} className={styles.link}>
delete ``

2023-07-22 15:37 UTC, creator-woow commented on src/pages/Product/ui/Page.tsx
> +    const { store, product } = useParams();
rename params names

2023-07-22 15:37 UTC, creator-woow commented on src/pages/Store/ui/Page.module.scss
> +.sectionFooter {
delete filter and search input styles, it's styles in components

2023-07-22 15:37 UTC, creator-woow commented on src/pages/Store/ui/Page.tsx
> +    useEffect(() => {
delete infinity scroll preparation

2023-07-22 16:32 UTC, VitaliyFrolov commented
added path to page

2023-07-22 16:34 UTC, merged